---
on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  "build-ubuntu":
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Set up"
        shell: "bash"
        run: |
          set -x
          sudo apt-get -qqqq update
          sudo apt-get -qqqq install software-properties-common
          sudo add-apt-repository "deb http://mirror.math.princeton.edu/pub/ubuntu kinetic main universe"
          sudo apt-get -qqqq update
          sudo apt-get -qqqq install tree xdg-user-dirs libwxgtk3.2-dev
          xdg-user-dirs-update --force
          mkdir home
          cd home
          mkdir .config
          mkdir .cache
          cd -

      - name: "Set up test"
        shell: "bash"
        env:
          "HOME": "${{ github.workspace }}/home"
        run: |
          set -x
          cd ~
          pwd
          env | grep -i xdg
          echo $HOME
          xdg-user-dirs-update --force
          xdg-user-dirs-update --set DOCUMENTS $HOME/MyDocs
          cat .config/user-dirs.dirs
          tree -a
          mv Documents MyDocs
          cd -

      - name: "Build"
        shell: "bash"
        run: |
          HOME=$saved_home
          cmake .
          cmake --build .

      - name: "Test"
        shell: "bash"
        run: "ctest -V"



  "build-macos":
    runs-on: "macos-12"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Build"
        shell: "bash"
        env:
          "HOMEBREW_NO_AUTO_UPDATE": "1"
        run: |
          set -x
          brew install wxwidgets
          cmake .
          cmake --build .

      - name: "Test"
        shell: "bash"
        run: "ctest -V"



  "build-windows":
    runs-on: "windows-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "msys2/setup-msys2@v2"
        with:
          release: false
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
            wxwidgets3.2-msw:p

      - name: "Build"
        shell: "msys2 {0}"
        run: |
          set -x
          cmake .
          cmake --build .

      - name: "Test"
        shell: "msys2 {0}"
        run: "ctest -V"
