---
on:
  push:
    branches:
      - "*"

jobs:
  "build-ubuntu":
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Build"
        shell: "bash"
        run: |
          set -x
          sudo apt-get -qqqq update
          sudo apt-get -qqqq install xdg-user-dirs libwxgtk3.0-gtk3-dev
          xdg-user-dirs-update --force
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: "Test"
        shell: "bash"
        run: "./build/datadirswx"



  "build-macos":
    runs-on: "macos-12"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Build"
        shell: "bash"
        run: |
          set -x
          HOMEBREW_NO_AUTO_UPDATE=1 brew install wxwidgets
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: "Test"
        shell: "bash"
        run: "./build/datadirswx.app/Contents/MacOS/datadirswx"
