---
on:
  push:
    branches:
      - "*"

jobs:
  "build-epple2-ubuntu":

    
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Build"
        shell: "bash"
        run: |
          set -x
          sudo apt-get -qqqq update
          sudo apt-get -qqqq install xdg-user-dirs libwxgtk3.0-gtk3-dev
          ls -l /home/runner
          ls -l /home/runner/.config
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: "Test"
        shell: "bash"
        run: "./build/datadirswx"
