---
on:
  push:
    branches:
      - "*"

jobs:
  "build-ubuntu":
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Build"
        shell: "bash"
        run: |
          set -x
          sudo apt-get -qqqq update
          sudo apt-get -qqqq install software-properties-common
          sudo add-apt-repository "deb http://mirror.math.princeton.edu/pub/ubuntu kinetic main universe"
          sudo apt-get -qqqq update
          sudo apt-get -qqqq install xdg-user-dirs libwxgtk3.2-dev
          xdg-user-dirs-update --force
          cmake .
          cmake --build .

      - name: "Test"
        shell: "bash"
        run: "ctest -V"



  "build-macos":
    runs-on: "macos-12"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Build"
        shell: "bash"
        run: |
          set -x
          HOMEBREW_NO_AUTO_UPDATE=1 brew install wxwidgets
          cmake .
          cmake --build .

      - name: "Test"
        shell: "bash"
        run: "ctest -V"



  "build-windows":
    runs-on: "windows-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "msys2/setup-msys2@v2"
        with:
          release: false
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
            wxwidgets3.2-msw:p

      - name: "Build"
        shell: "msys2 {0}"
        run: |
          set -x
          cmake .
          cmake --build .

      - name: "Test"
        shell: "msys2 {0}"
        run: "ctest -V"

      - name: "APPDATA test"
        shell: "pwsh"
        run: |
          Set-PSDebug -Trace 1
          mkdir D:\a\_temp\foo
          .\testenv.ps1 -RunAsAdmin
          $env:APPDATA

      - name: "Test2"
        shell: "msys2 {0}"
        run: |
          echo $APPDATA
          ctest -V
